openapi: '3.0.3'
info:
  title: Centre commercial
  version: '1.0'


security:
  - BearerAuth: [ ]
paths:
# Authentification
## Registration endpoint
  /api/auth/register:
    post:
      tags:
        - Security
      security: []
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Registration"

      responses:
        '201':
          description: Registration successful, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the registration was successful
                  message:
                    type: string
                    description: Additional message about the registration attempt
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        description: The JWT token to be used for authenticated requests
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            description: The unique identifier of the user
                          email:
                            type: string
                            format: email
                            description: The email address of the user
                          role:
                            type: string
                            description: The role of the user (e.g., admin, user)
                          status:
                            type: string
                            description: The status of the user (e.g., active, pending)
        '400':
          description: Bad Request, invalid input data or user already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the registration was successful
                  message:
                    type: string
                    description: Additional message about the registration attempt
## Login endpoint
  /api/auth/login:
    post:
      tags:
        - Security
      security: []
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        '200':
          description: Login successful, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the login was successful
                  message:
                    type: string
                    description: Additional message about the login attempt
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        description: The JWT token to be used for authenticated requests
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            description: The unique identifier of the user
                          email:
                            type: string
                            format: email
                            description: The email address of the user
                          role:
                            type: string
                            description: The role of the user (e.g., admin, user)
        '401':
          description: Unauthorized, invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the login was successful
                  message:
                    type: string
                    description: Additional message about the login attempt
  /api/auth/logout:
    post:
      tags:
        - Security
      operationId: logout
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the logout was successful
                  message:
                    type: string
                    description: Additional message about the logout attempt
        '401':
          description: Unauthorized, user not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the logout was successful
                  message:
                    type: string
                    description: Additional message about the logout attempt
components:
  schemas:
    Registration:
      type: object
      required:
        - email
        - password
      parameters:
        - in: body
          name: user
          description: User registration data
          required: true
          schema:
            type: object
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          format: password
          description: User's password
        firstName:
          type: string
          description: User's first name
        lastName:
          type: string
          description: User's last name
        role:
          type: string
          description: User's role (e.g., admin, user)
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          format: password
          description: User's password
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
